# Generated by Django 5.2.16 on 2026-08-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_article_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('video', 'Video'), ('short', 'Short'), ('image', 'Image')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('caption', models.TextField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='gallery/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/thumbs/')),
                ('order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
